---
- hosts: sgcc-hosts
  remote_user: baoadmin
  become: yes
  vars:
    change_user: baoadmin
    passwd_file_path: /deployment/ansible-playbooks/password.txt
  tasks:
    - name: generate password
      local_action: command python /deployment/ansible-playbooks/password.py
      register: password
    - debug: msg="{{ inventory_hostname }}"
    - debug: var="password.stdout"

    - name: Encryption string
      local_action: command python -c "from passlib.hash import sha512_crypt; print sha512_crypt.using(rounds=5000).hash('''{{password.stdout}}''')"
      register: passwd
    - debug: var="passwd.stdout"

    - name: change baoadmin password
      user: name={{ change_user }} password={{ passwd.stdout }} update_password=always

    - name: save the password
      local_action: lineinfile  dest="{{ passwd_file_path }}"  line="{{ inventory_hostname }}   {{ password.stdout }}" create=yes state=present
